"use client"

import { MotorParams } from '../MotorControlClient'

export type componentProps = { motorNumber: number, state: MotorParams, setState: (motorState: MotorParams) => void, frameStyle?: {}}
export type switchComponentProps = componentProps
export type sliderComponentProps = componentProps

export { AlertPinPolaritySwitch } from './AlertPinPolaritySwitch'
export { AutodeadtimeSwitch } from './AutodeadtimeSwitch'
export { BrakePolaritySwitch } from './BrakePolaritySwitch'
export { BrakeTimeSlider } from './BrakeTimeSlider'
export { BrakingModeSwitch } from './BrakingModeSwitch'
export { ChangeDutySlider } from './ChangeDutySlider'
export { ChargePumpState } from './ChargePumpState'
export { ChargePumpStateMonitoringSwitch } from './ChargePumpStateMonitoringSwitch'
export { CurrentSenseFilteringSlider } from './CurrentSenseFilteringSlider'
export { CurrentSenseGainSwitch } from './CurrentSenseGainSwitch'
export { CurrentState } from './CurrentState'
export { DeadtimeSlider } from './DeadtimeSlider'
export { DigitalFilteringSlider } from './DigitalFilteringSlider'
export { DirectionSwitch } from './DirectionSwitch'
export { DutyUpTimeSwitch } from './DutyUpTimeSwitch'
export { ElectricalAngleMaxFrequencySlider } from './ElectricalAngleMaxFrequencySlider'
export { ErrorBrakingModeSwitch } from './ErrorBrakingModeSwitch'
export { ErrorLatchSwitch } from './ErrorLatchSwitch'
export { FirstDCExcitationTimeSlider } from './FirstDCExcitationTimeSlider'
export { ForcedComutationFrequencySlider } from './ForcedComutationFrequencySlider'
export { ForcedComutationSwitch } from './ForcedComutationSwitch'
export { GateSinkCurrentSlider } from './GateSinkCurrentSlider'
export { GateSourceCurrentSlider } from './GateSourceCurrentSlider'
export { KISlider } from './KISlider'
export { KIXSwitch } from './KIXSwitch'
export { KPSlider } from './KPSlider'
export { KPXSwitch } from './KPXSwitch'
export { LeadAngleSlider } from './LeadAngleSlider'
export { MaxDutyHysteresisSlider } from './MaxDutyHysteresisSlider'
export { MaxDutySlider } from './MaxDutySlider'
export { MaxOffSwitch } from './MaxOffSwitch'
export { MaxOpenSwitch } from './MaxOpenSwitch'
export { MaxSpeedSlider } from './MaxSpeedSlider'
export { MotorDutySlider } from './MotorDutySlider'
export { NoStopSwitch } from './NoStopSwitch'
export { OffDutySlider } from './OffDutySlider'
export { OpenLoopSwitch } from './OpenLoopSwitch'
export { OutputCurrentMonitoringSwitch } from './OutputCurrentMonitoringSwitch'
export { OutputPWMSlider } from './OutputPWMSlider'
export { OverCurrentDetectionSwitch } from './OverCurrentDetectionSwitch'
export { OvercurrentDetectionThresholdSwitch } from './OvercurrentDetectionThresholdSwitch'
export { PolesSlider } from './PolesSlider'
export { PositionDetectionHysteresisSlider } from './PositionDetectionHysteresisSlider'
export { PostBrakingActionSwitch } from './PostBrakingActionSwitch'
export { RPMLimitSlider } from './RPMLimitSlider'
export { RestartTimeSlider } from './RestartTimeSlider'
export { RotationState } from './RotationState'
export { SecondDCExcitationTimeSlider } from './SecondDCExcitationTimeSlider'
export { SoftStartCurrentLimitSlider } from './SoftStartCurrentLimitSlider'
export { SoftStartCurrentStepSizeSlider } from './SoftStartCurrentStepSizeSlider'
export { SoftStartSpeedChangeLimitSlider } from './SoftStartSpeedChangeLimitSlider'
export { SpeedChangeLimitSlider } from './SpeedChangeLimitSlider'
export { SpeedInputInversionSwitch } from './SpeedInputInversionSwitch'
export { SpeedInputModeSwitch } from './SpeedInputModeSwitch'
export { SpeedOutputModeSwitch } from './SpeedOutputModeSwitch'
export { SpeedSlope2Slider } from './SpeedSlope2Slider'
export { SpeedSlopeSlider } from './SpeedSlopeSlider'
export { StandbyModeSwitch } from './StandbyModeSwitch'
export { StartDutySlider } from './StartDutySlider'
export { StartRPMSlider } from './StartRPMSlider'
export { StartupCurrentLimitSlider } from './StartupCurrentLimitSlider'
export { StartupState } from './StartupState'
export { TemperatureState } from './TemperatureState'
export { ThermalShutdownInhibitSwitch } from './ThermalShutdownInhibitSwitch'
export { DutyCurve } from './MotorDutyCurve'
export { RPMErrorState } from './RPMErrorState'